# Generated by Django 4.0.2 on 2022-04-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0002_books_info_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_info',
            name='category',
            field=models.CharField(default='NULL', max_length=300),
        ),
        migrations.AlterField(
            model_name='books_info',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
