# Generated by Django 4.0.2 on 2022-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0003_books_info_category_alter_books_info_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=150)),
                ('stu_roll', models.IntegerField()),
            ],
        ),
    ]
